
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esteban-cv-https
    restart: unless-stopped
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - TZ=America/Mexico_City
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network
      
networks:
  portfolio-network:
    driver: bridge

  
